[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv",
    "/opt/venv/bin/pip install --upgrade pip",
    "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "PYTHONPATH=/app:$PYTHONPATH /opt/venv/bin/python3 apps/bot/main.py"
