[build]
builder = "NIXPACKS"

[deploy]
startCommand = "/opt/venv/bin/python3 apps/bot/main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.environmentVariables]]
name = "PYTHONPATH"
value = "/app"
